# This is a template configuration file for Travis CI, for testing
# your tutorial regularly. Copy it to .travis.yml in the top level
# directory of your tutorial, in the master branch.

sudo: false
language: python
dist: xenial
python:
  - 2.7
  - 3.7
env:
  global:
  - IMP_BRANCH=develop
  - IMP_BRANCH=master
  - secure: Y6KvUqrfm1uCxiY9rwGKHoUVrYjKSv0au8KMBpfXhRHNz+fnVsTXy5w7ovhceCvqwC+HxXuwnSDHbflw0ybNI+5tOqnGlcrGQV/U9paLMvlZ6ynFZguTU+7dNfbV2i+8bX/InKf1+/rcr5mlsUOfXGf8j+XSY6v6/BTy4sEI+N29/Rof/j8xlH4hncr9idRPu6KPrHHWzgohdmplXX3omuUbFAMPK5uNflPWk6uh2Ws57TWbZinmCg5fcGLXYjqXCKkZXTtMXSYyOJpAQB/JV/aI4qMXqwwJ5Y5DV8CNiD97PkMGLgFCmlV6XW+ZgnpIj28bNstZrh8gOAsuZAi8yU4eeAWP+CMl3Oa2c5v8pxNtzypCs9xqWLx0ijiDrtPRRUwuv2bc+Qn9MCsUw2H74NTl2I+/erSCiIsRHuJWpstiCt2/OwNj6HDHQWgM4v3hR0N2xi4GWTzg3DwNkx6ieXj2Tq0alVx1uPje5DA85V5jZiTo+toYtp8NTXxHDLTYiRyFLOueZUWHYNxOSn8+moXFpjqVDa2ZoH34oksuL1V+cu32xRtpP9RSGoe1Jj7ADMg/SnkK0iUAcXTU4y7ZisU4I0Ou+jXSzmsKNhwRuwWo9MaG+zZYzzg7AKDngkqles8RjmLNdPWJCOQ4e07PIuhFJTqVT5xqVy0GOIn0d/E=
addons:
  apt:
    packages:
    - gnuplot
install:
  - wget -q $LICENSE_URL -O mod-license >& /dev/null
  - KEY_MODELLER=`cat mod-license` support/setup_travis.sh $HOME/conda $IMP_BRANCH $TRAVIS_PYTHON_VERSION
  - source $HOME/conda/bin/activate python$TRAVIS_PYTHON_VERSION
  - python -V
script:
  - nosetests --exe support/test
